---
- name: checkout
  hosts: localhost
  vars:
    # git_protocol: git@github.com:
    git_protocol: https://github.com/

  pre_tasks:
    - name: Install roles from Ansible Galaxy
      become: true
      shell: ansible-galaxy install -r requirements.yml
    - name: Store passphrase
      shell: ssh-add ~/.ssh/github/id_rsa-private-key-ssh2-rsa
      ignore_errors: yes

  roles:
   - name: cmod-migration
     role: cchurch.scm
     scm_url: "{{ git_protocol }}francisoud/cmod-migration.git"
     scm_target_path: ./code/perso/github/cmod-migration
     scm_version: master
   - name: googlecalendar
     role: cchurch.scm
     scm_url: "{{ git_protocol }}francisoud/googlecalendar.git"
     scm_target_path: ./code/perso/github/googlecalendar
     som_version: master
   - role: cchurch.scm
     scm_url: "{{ git_protocol }}francisoud/android-transfer.git"
     scm_target_path: ./code/perso/github/android-transfer
     scm_version: master
   - role: cchurch.scm
     scm_url: "{{ git_protocol }}francisoud/francisoud-sandbox.git"
     scm_target_path: ./code/perso/github/francisoud-sandbox
     scm_version: master
   - role: kbrebanov.subversion
     become: true

